### ISSUE TITLE
Incorrect information in release notes for BlueXP Audit API

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/bluexp-relnotes#37]
### Page URL

https://docs.netapp.com/us-en/bluexp-relnotes/whats-new.html

### Page title

Recent changes in BlueXP

### Summary

The release notes for the BlueXP Audit API state:

"The audit service records information about the operations performed by BlueXP services. This includes the **originating IP addresses**, workspaces, Connectors used, and other telemetry data. You can use this data to determine what actions were performed, who performed them, and when they occurred."

An "originating IP address" is not actually included in the output of the audit API, so mention of IP Address should be removed from the release notes.  Example output record is pasted below, illustrating the lack of an originating IP address field.

```
    {
        "accountId": "account-<redact>",
        "principalId": "auth0|646b649eed8833d52cxxxxxxx",
        "workspaceId": null,
        "agentId": null,
        "agentName": null,
        "resourceId": null,
        "resourceName": null,
        "action": "Create service account",
        "startTime": 1691510207892,
        "endTime": 1691510210225,
        "status": "success",
        "requestId": "wXZldYxxxxx",
        "service": "tenancy",
        "requestData": "{\"method\":\"POST\",\"url\":\"/tenancy/external/account/account-xxxxxxx/service-account\",\"body\":{\"serviceAccountName\":\"testsa\",\"rolePublicId\":\"Role-1\",\"workspacePublicIds\":[]}}",
        "responseData": "{\"statusCode\":200,\"response\":{\"clientId\":\"xxxxxxxxx\",\"clientSecret\":\"******\",\"publicId\":\"user-xxxxxxxx\"}}",
        "hasRecords": false,
        "hasFailedRecord": false,
        "lastModified": 1691510212039
    },
```

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@mimitche,

Thank you for reaching out with this feedback. The description in the release notes was pulled from the summary of the API found here: https://docs.netapp.com/us-en/bluexp-automation/audit/overview.html

I'll work with the developer to ensure that the description for the API is accurate.

Thanks,
Ben

**Comment by netapp-bcammett** [comment]
The phrase "originating IP address" was removed from the release notes. I'll work separately with the API developer to ensure that the description of the API is accurate.

Thanks again,
Ben
